version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: tasktracker_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-tasktracker_db}
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    ports:
      - "${POSTGRES_PORT:-5555}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
